version: '3.8'

volumes:
  ubs-veeam_dashboard:
    external: true

services:
  veeam-dashboard:
    build: .
    container_name: veeam-dashboard
    ports:
      - "5000:5000"
    environment:
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ubs-veeam_dashboard:/data
    restart: unless-stopped
    stdin_open: true
    tty: true
